### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by ThibaudDauce** [datagouv/front-end#38]
# Done

- [x] Active state of admin menu
- [x] Full width tables
- [x] Publish on button (data.gouv.fr text + placeholder images for different types)
- [x] Me profile?
- [x] Fluid header is broken?
- [x] Dataservices (admin + publishing form)
- [x] Add an AccordionGroup (for the profile, publishing form and sidebar)
- [x] Migrate header menu
- [x] /newadmin redirect to org / me
- [x] move from /newadmin to /beta/admin
- [x] #30
- [x] soucis de redirection à enquêter : https://dev.data.gouv.fr/en/beta/admin/organizations/646b7187b50b2a93b1ae3d45/dataservices envoie vers la home

# Priorité 1

- [x] Page title in head datagouv/front-end#115
- [x] Full height bg-gray #101
- [x] Add back toasts in @ThibaudDauce pages #102
- [x] Add toast in case of API error datagouv/front-end#100
- [x] Breadcrumb links datagouv/front-end#114
- [x] rajouter un bandeau sur nouvelle admin pour rediriger vers ancienne admin https://github.com/datagouv/front-end/pull/125
- [x] dans le front-end, rediriger (temporairement) vers la vieille admin sur le bouton administration
- [x] enlever la page https://dev.data.gouv.fr/fr/beta/admin/me #103
- [x] rajouter un favicon datagouv/front-end#104
- [x] enlever la home v1 Nuxt ou mettre une redirection #103
- [x] régler les couleurs input markdown
- [x] redirection des steps
- [x] rajouter le lien vers l'édition des ressources sur la vieille admin datagouv/front-end#113
- [x] corriger l'affichage de multiples tags avec du wrap datagouv/front-end#106
- [x] remplacer "What is a dataservice?" par Reuse sur le parcours datagouv/front-end#107 datagouv/front-end#108
- [x] soucis sur l'édition de l'image de la reuse? datagouv/front-end#111
- [x] soucis sur le bouton gérer à la fin du parcours orga https://github.com/datagouv/front-end/pull/123
- [x] lien sur feedback parcours de publication à distinguer entre les différents parcours https://github.com/datagouv/front-end/pull/120
- [x] à la fin du parcours publication, le bouton publier amène sur une 404 Nuxt au lieu de router vers udata-front https://github.com/datagouv/front-end/pull/124
- [x] sauvegarder en brouillon à l'étape 3
- [x] remplacer "accéder à l'espace catalogage" par https://guides.data.gouv.fr/autres-ressources-utiles/catalogage-de-donnees-grist datagouv/front-end#109
- [x] rajouter une barre de scroll dans la modale de ressources
- [x] déployer nouvelle version sur la prod
- [x] rajouter un bandeau sur la vieille admin pour rediriger vers la nouvelle https://github.com/opendatateam/udata/pull/3194
- [x] certaines pages d'édition ont les boutons du champ input markdown qui font un submit ([exemple](https://dev.data.gouv.fr/fr/beta/admin/organizations/646b7187b50b2a93b1ae3d45/reuses/66feab3f18e90a45f864f093))
- [x] dès qu'on est ready, merger la PR pour le bouton publier
- [x] créer et brancher un projet sentry https://github.com/datagouv/front-end/pull/146
- [x] Translations https://github.com/datagouv/front-end/pull/155
- [x] rajouter une page 404 https://github.com/datagouv/front-end/pull/143
- [x] règle validation reuses https://github.com/datagouv/front-end/pull/149
- [x] ajouter les boutons supprimer sur l'édition des dataservices, reuses, datasets https://github.com/datagouv/front-end/pull/134
- [x] lorsque l'on publie un dataservice si l'on revient en arrière et qu'on chosit enregistrer en brouillon les deux contenus sont crée
- [x] sur tous les parcours, ajouter la création au fil de l'eau et non à la fin
- [x] Vérifier pourquoi mes jeux de données n’apparaissent pas dans mon admin personnel.

# Priorité 2

- [x] rajouter bouton voir page public sur tous les objets datagouv/front-end#112
- [x] soucis de génération API key https://github.com/datagouv/front-end/pull/122
- [x] licence : étoile bleue n'apparaît pas
- [x] perte des images sur les boutons d'accueil du parcours de publication dataset
- [x] rajouter une route health
- [x] finir édition des datasets (selon difficulté) https://github.com/datagouv/front-end/pull/163
- [x] Loading state of tables
- [x] rajouter un bouton précédent dans les parcours
- [x] améliorer alignement bouton Publier sur data.gouv.fr
- [x] décaler les logos dans la liste Publier sur data.gouv.fr
- [x] réordonner les élements dans Publier sur data.gouv.fr pour avoir orga en dernier (même ordre sur front-end et udata-front)
- [ ] taille des colonnes instables
- [x] rejouer la validation qualité lorsqu'on entre sur l'édition d'un contenu https://github.com/datagouv/front-end/pull/152
- [x] dans l'édition d'un JDD, remplacer les "onglets" par les tabs DSFR
- [x] au multi-select, afficher au clic la liste des suggests déjà fetchs (ex : licence, orga) https://github.com/datagouv/front-end/pull/139 https://github.com/datagouv/front-end/pull/139
- [ ] désuniquifier les tags et les slugifier
- [x] enlever le warning description lors de l'upload d'un fichier https://github.com/datagouv/front-end/pull/153
- [x] le champ description d'une ressource doit être markdown https://github.com/datagouv/front-end/pull/153
- [x] ajouter les boutons de transfert sur les reuses, datasets, dataservices
- [x] ajouter les boutons d'archivage sur les reuses, datasets, dataservices
- [x] Ajouter un bouton "passer en brouillon" ou "passer en public" sur la modification des objets (reuses, datasets, dataservices) dans l'admin
- [x] Il manque le favicon. https://github.com/datagouv/front-end/pull/195
- [x] **En savoir plus sur le moissonnage** : utiliser le lien correct [guide-data.gouv.fr/moissonnage](https://guides.data.gouv.fr/guide-data.gouv.fr/moissonnage).
- [x] Le check de documentation ne fonctionne pas lorsqu’un fichier de type documentation est ajouté.
- [x] Rajouter le support du mode READ ONLY (bannière d'info et enlever les boutons publier principaux) 
 
# Priorité 3
- [x] manque l'icône sur le nom du user courant dans le header
- [ ] Stats (datasets, reuses, discussions, dataservices ?)
- [x] -manque de la description sur la carte orga à la fin du parcours orga
- [x] full width sur la carte dataset lors de la sélection des JDDs associés lors du parcours dataservice (et reuse?)
- [x] Les entêtes de tableau s’affichent brièvement avant l’empty state.
- [ ] #205
- [x] **Profil** : la biographie peut être moins grande (ce type d’inputs peut être redimensionné normalement).
- [x] #177
- [x] Ajouter l’empty state des moissonneurs [voir le design](https://www.figma.com/design/YbluH37N5lpcM0SgF65LdD/%E2%9A%99%EF%B8%8F-Administrations-et-modification-des-jeux-de-donn%C3%A9es?node-id=2192-19754&t=7kfBDoAIdKFJahnB-4).
- [x] Sur les descriptions d’organisation, le check se fait au clic et pas avant.
- [x] Réduire l’espace trop important entre la couverture spatiale et la granularité spatiale.
- [x] Vérifier pourquoi les checks ne fonctionnent pas sur les jeux de données.
- [x] #201
- [x] Dans le tooltip de choix de licence, la licence ouverte (en dessous de tout producteur) ne réagit pas au hover.
- [x] #230
- [ ] Récuperer les configs depuis udata (pour avoir udata.cfg en seule source de vérité)

**Comment by nicolaskempf57** [comment]
Les points restants ont été transférés dans des tickets séparés
