### ISSUE TITLE
TODO parcours datasets

### ISSUE THREAD

**Issue by ThibaudDauce** [datagouv/front-end#47]
- [x] ajouter publish dataset button quelque part ?
- [x] add field name in required rule https://github.com/datagouv/front-end/pull/54

# step 2

- [x] recherche dans le champs identité https://github.com/datagouv/front-end/pull/49
- [x] bordure gauche des inputs qui disparaît https://github.com/datagouv/front-end/pull/50
- [x] debounce search in searchableselect? https://github.com/datagouv/front-end/pull/56
- [x] add new option from scratch in searchableselect (tags) https://github.com/datagouv/front-end/pull/52
- [x] traduction It's advised to have a description of at least {min} characters. https://github.com/datagouv/front-end/pull/53

# step 3

- [x] design drag and drop zone https://github.com/datagouv/front-end/pull/58
- [x] delete bouton rounded dans la liste dans le add file modal? https://github.com/datagouv/front-end/pull/58

# step 4

- [x] modifier le texte "Your dataset is created !" car le dataset n'est plus sauvegardé à ce moment là, il faut attendre le cliquer sur « publier » ou « sauvegarder en brouillon » pour le stockage  https://github.com/datagouv/front-end/pull/59
- [x] bouton overlap avec la cadre bleu https://github.com/datagouv/front-end/pull/62
- [x] centrage? https://github.com/datagouv/front-end/pull/59
- [x] multipart upload

**Comment by nicolaskempf57** [comment]
@ThibaudDauce I think we can close this one
